[Import subscriber] Added support to merge exisitng subscribers' attributes
joshtechnologygroup/listmonk pull request #1
Opened 2024-02-26 11:53 UTC by srishti-vishnoi

**Issue:**
Currently, when importing subscribers via CSV, the system only allows for overwriting or skipping existing subscribers. The system cannot merge user attributes with existing ones.

**Proposed Solution:**
To address this limitation, I've implemented support for merging user attributes during CSV import. Users now have the option to choose whether to merge attributes when overwriting is set to False.

**Key Points:**

Overwrite? | Merge? | Expected Result
-- | -- | --
TRUE | TRUE | Merge Ignored  (toggle hidden) (NOT POSSIBLE)
TRUE | FALSE | Merge Ignored (toggle hidden) (NOT POSSIBLE)
FALSE | TRUE | Subscribers' data will be merged
FALSE | FALSE | Subscribers will be skipped during import (No change)

*Additional Notes:*

1. When overwrite is set to True, the Merge toggle will be hidden and the value of the Merge flag will be set to False.
2. The Import subscriber API will now throw a Bad Request error if both merge and overwrite are set to True, preventing conflicting settings.

This enhancement ensures a more flexible and intuitive subscriber management process during CSV imports.

Screenshots:
![Screenshot from 2024-02-26 16-38-41](https://github.com/joshtechnologygroup/listmonk/assets/78725309/07549fb7-8c78-4c64-b3e4-a67542229a21)

2024-02-26 13:12 UTC, sandipagarwal requested changes

2024-02-26 13:12 UTC, sandipagarwal commented on cmd/import.go
> -
Don't make a change that is not required.

2024-02-26 13:12 UTC, sandipagarwal commented on i18n/en.json
> +    "import.mergeHelp": "Merge attribs of existing subscribers?",
`Merge attributes of existing subscribers?`

2024-02-26 13:12 UTC, sandipagarwal commented on queries.sql
> +        ),
Please update the comments that are present above this query.

2024-02-26 13:12 UTC, sandipagarwal commented on queries.sql
> +            ELSE s.attribs END
Can this be optimised?

2024-02-27 12:31 UTC, srishti-vishnoi commented on queries.sql
> +            ELSE s.attribs END
As discussed, this is no more required

2024-02-28 06:15 UTC, sandipagarwal approved these changes

2024-02-28 06:15 UTC, sandipagarwal commented on queries.sql
> +            ELSE s.attribs END
Not required anymore.

2024-02-28 08:21 UTC, merged